/**
 * Photo Control — Prompt Composer
 *
 * Pure, framework-free module that composes the mutation prompt sent to the
 * Gemini image-generation model. The composed prompt contains:
 *
 *  - The natural-language directive (what to change).
 *  - The original `MinimalSchema` as a compact JSON anchor (grounding for
 *    unchanged attributes). (Requirement 11.2)
 *  - The target `MinimalSchema` as a compact JSON anchor (desired end state).
 *
 * Design notes:
 *  - The `Minimal_Schema` is intentionally tiny, so compact JSON serialization
 *    keeps the composition extremely compact in normal usage.
 *  - All validation is done before serialization so callers receive a clear
 *    error message identifying which component is missing or unencodable.
 *  - This module has no I/O, no framework dependencies, and no mutable state.
 *    It is a pure mapping from `CompositionInput` to `CompositionResult`.
 *
 * Requirements: 10.1, 11.2
 */

import type { MinimalSchema } from './minimal-schema'

// ============================================================================
// Types
// ============================================================================

/**
 * The required inputs for composing a mutation prompt.
 *
 * All three fields are required; `composePrompt` returns a
 * `COMPOSITION_FAILURE` when any is missing or unencodable.
 * (Requirements 10.1, 10.6, 16.1)
 */
export interface CompositionInput {
  /** The natural-language instruction generated by the Directive_Generator. */
  directive: string
  /** The current (original) editor state schema — grounding anchor. (Requirement 11.2) */
  originalState: MinimalSchema
  /** The desired (target) editor state schema. */
  targetState: MinimalSchema
}

/**
 * Discriminated-union result of `composePrompt`.
 *
 * On success, `prompt` is the composed string ready to pass to
 * `NanoBananaClient`. On failure, `error` describes the problem and `code` is
 * always `'COMPOSITION_FAILURE'`. (Requirement 10.6)
 */
export type CompositionResult =
  | { ok: true; prompt: string }
  | { ok: false; error: string; code: 'COMPOSITION_FAILURE' }

// ============================================================================
// Error class
// ============================================================================

/**
 * Thrown by callers that prefer exceptions over discriminated-union results.
 *
 * `composePrompt` itself returns a `CompositionResult`; this class is provided
 * for convenience when the caller wants to throw instead of check.
 * (Requirement 10.6)
 */
export class CompositionFailureError extends Error {
  readonly code = 'COMPOSITION_FAILURE' as const

  constructor(message: string) {
    super(message)
    this.name = 'CompositionFailureError'
  }
}

// ============================================================================
// Internal helpers
// ============================================================================

/**
 * Generate a camera specification object based on the target angle.
 * Incorporates industry-standard terms and synonyms for better model guidance.
 */
function getCameraSpecification(angle: string) {
  switch (angle) {
    case 'top-down':
      return {
        pitch: '90°',
        term: 'Top-Down',
        lens: '35mm/50mm',
        aperture: 'f/8.0',
        focus: 'deep',
      }
    case '45-degree':
      return {
        pitch: '45°',
        term: '3/4 View',
        lens: '50mm',
        aperture: 'f/2.8',
        focus: 'shallow',
      }
    case 'eye-level':
      return {
        pitch: '0°',
        term: 'Table-top horizon',
        constraints: {
          instruction: 'Plate as flat line, no overhead view.',
          denial: 'Top surface not visible.',
        },
        lens: '85mm',
        aperture: 'f/1.8',
        focus: 'shallow',
      }
    case 'macro-close-up':
      return {
        pitch: 'var',
        term: 'Macro',
        lens: '100mm',
        aperture: 'f/2.8',
        focus: 'v. shallow',
      }
    default:
      return {
        pitch: 'var',
        term: `${angle}`,
        lens: 'std',
        aperture: 'f/2.8',
        focus: 'std',
      }
  }
}

/**
 * Fixed final image metadata for consistent output quality.
 */
const FINAL_IMAGE_META = {
  style: 'photorealistic',
  format: 'high-res JPG',
  framing: 'full shot, no cropping',
}

/**
 * Returns a `COMPOSITION_FAILURE` result with the given message.
 */
function failure(error: string): CompositionResult {
  return { ok: false, error, code: 'COMPOSITION_FAILURE' }
}

// ============================================================================
// Public API
// ============================================================================

/**
 * Compose the mutation prompt from the directive and compact JSON anchors.
 *
 * The prompt format is:
 * ```
 * {directive}
 *
 * Original state: {originalJSON}
 * Target state: {targetJSON}
 *
 * Camera specification: {cameraSpecJSON}
 * Final image meta: {finalMetaJSON}
 * ```
 *
 * Validation steps (in order):
 *  1. `directive` must be a non-empty string.
 *  2. `originalState` and `targetState` must be non-null objects.
 *  3. Both states must be JSON-serializable (try/catch around `JSON.stringify`).
 *
 * Returns `{ ok: true, prompt }` on success.
 * Returns `{ ok: false, error, code: 'COMPOSITION_FAILURE' }` on any failure.
 *
 * (Requirements 10.1, 11.2)
 */
export function composePrompt(input: CompositionInput): CompositionResult {
  const { directive, originalState, targetState } = input

  // ── 1. Validate directive ─────────────────────────────────────────────────
  // (Requirement 10.6)
  if (typeof directive !== 'string' || directive.trim().length === 0) {
    return failure('Composition failure: directive is missing or empty.')
  }

  // ── 2. Validate state objects ─────────────────────────────────────────────
  // (Requirements 10.1, 16.1)
  if (
    originalState === null ||
    originalState === undefined ||
    typeof originalState !== 'object'
  ) {
    return failure(
      'Composition failure: originalState is missing or not an object.',
    )
  }
  if (
    targetState === null ||
    targetState === undefined ||
    typeof targetState !== 'object'
  ) {
    return failure(
      'Composition failure: targetState is missing or not an object.',
    )
  }

  // ── 3. Serialize states as compact JSON (no whitespace) ───────────────────
  // (Requirements 11.2, 16.1)
  // We keep the structure but use very short keys to stay under budget.
  const compress = (s: any) => ({
    s: {
      a: s.scene_setup.angle,
      f: s.scene_setup.framing,
      l: s.scene_setup.lighting,
      sp: s.scene_setup.spin ?? '0',
    },
    c: {
      b: s.canvas.background.slice(0, 50),
      bs: (s.canvas.background_style ?? '').slice(0, 40),
      v: s.canvas.main_vessel.slice(0, 50),
    },
    f: {
      m: s.food_components.main_item.slice(0, 100),
      g: s.food_components.garnishes.map((g: string) => g.slice(0, 50)),
      si: s.food_components.sides.map((si: string) => si.slice(0, 50)),
    },
  })

  let originalJSON: string
  let targetJSON: string

  try {
    originalJSON = JSON.stringify(compress(originalState))
  } catch (err) {
    return failure(
      `Composition failure: originalState could not be serialized to JSON. ${
        err instanceof Error ? err.message : String(err)
      }`,
    )
  }

  try {
    targetJSON = JSON.stringify(compress(targetState))
  } catch (err) {
    return failure(
      `Composition failure: targetState could not be serialized to JSON. ${
        err instanceof Error ? err.message : String(err)
      }`,
    )
  }

  // ── 4. Generate additional metadata ───────────────────────────────────────
  const cameraSpec = getCameraSpecification(targetState.scene_setup.angle)
  const cameraSpecJSON = JSON.stringify(cameraSpec)
  const finalMetaJSON = JSON.stringify(FINAL_IMAGE_META)

  // ── 5. Compose the prompt ─────────────────────────────────────────────────
  // Format: directive + blank line + original anchor + target anchor + meta.
  // (Requirements 10.1, 11.2, 16.1)
  // MANDATORY: For eye-level shots, we add a strong override to the very beginning
  // of the prompt to ensure it's not ignored by the model's reference image processing.
  const isEyeLevel = targetState.scene_setup.angle === 'eye-level'
  const prefix = isEyeLevel 
    ? 'CRITICAL: CHANGE PERSPECTIVE TO SIDE-VIEW. IGNORE THE ANGLE OF THE REFERENCE IMAGE. ' 
    : ''

  const prompt = [
    prefix + directive,
    '',
    `Original: ${originalJSON}`,
    `Target: ${targetJSON}`,
    '',
    `Camera: ${cameraSpecJSON}`,
    `Meta: ${finalMetaJSON}`,
  ].join('\n')

  return { ok: true, prompt }
}
