/**
 * Photo Control — Prompt Composer
 *
 * Assembles the model-facing Tier 2 scene descriptor with a concise,
 * constrained-edit wrapper. The descriptor is built by `scene-descriptor` for
 * the Studio path; the legacy state pair remains accepted for callers that
 * have not yet migrated to pass the descriptor directly.
 */

import type { MinimalSchema } from './minimal-schema'
import type { SceneDescriptor } from './scene-descriptor'
import { STUDIO_BACKDROP_KEYS } from '@/lib/studio/backdrop-keys'
import { STUDIO_LIGHTING_KEYS } from '@/lib/studio/lighting-keys'
import { STUDIO_SURFACE_KEYS } from '@/lib/studio/surface-keys'

// ============================================================================
// Types
// ============================================================================

/** Inputs accepted while callers migrate from Tier 1 states to Tier 2. */
export interface CompositionInput {
  /** Natural-language instruction generated by the directive generator. */
  directive: string
  /** Model-facing Tier 2 descriptor, preferred by the Studio path. */
  descriptor?: SceneDescriptor
  /** Legacy Tier 1 state retained for existing admin and route callers. */
  originalState?: MinimalSchema
  /** Legacy Tier 1 target state retained for existing admin and route callers. */
  targetState?: MinimalSchema
}

/** Result of composing a prompt; the failure code is part of the route contract. */
export type CompositionResult =
  | { ok: true; prompt: string }
  | { ok: false; error: string; code: 'COMPOSITION_FAILURE' }

/** Convenience error for callers that prefer exceptions over result checking. */
export class CompositionFailureError extends Error {
  readonly code = 'COMPOSITION_FAILURE' as const

  constructor(message: string) {
    super(message)
    this.name = 'CompositionFailureError'
  }
}

/**
 * Ours, not Gemini's. Flash Image accepts ~131k input tokens and Pro Image ~64k
 * (including the reference image). 100k characters is a runaway-construction
 * tripwire (~25-50k text tokens), still below both model windows. Edit and
 * reshoot share it so a richer observed description cannot fail composition on
 * the reshoot path.
 */
const MAX_PROMPT_LENGTH = 100_000

const MAX_PROMPT_LENGTH_BY_TASK = {
  edit: MAX_PROMPT_LENGTH,
  reshoot: MAX_PROMPT_LENGTH,
} as const

/** Floor for a trimmed description; below this the text stops being useful. */
const MIN_DESCRIPTION_LENGTH = 50

/**
 * This is deliberately a real edit wrapper rather than a one-line preamble.
 * `locked` is the semantic negative prompt: it identifies the pixel-faithful
 * content without repeating a prohibition wall from every style row.
 */
const TASK_FRAMING = {
  edit:
    'Constrained edit: change only what "target" names; keep everything else exactly as-is; preserve the original composition. Semantic negative prompt: "subject.locked" remains pixel-faithful.',
  editWithCamera:
    'Constrained edit: change only what "target" names. If target.camera is present, photograph the same dish from that viewpoint; keep unnamed elements. Do not preserve the original camera height. Semantic negative prompt: "subject.locked" remains faithful; camera height may change.',
  reshoot:
    'Re-shoot: re-photograph the dish shown in the reference image. Rebuild composition, camera geometry, lighting and backdrop per "target". Preserve everything listed in "subject.locked" exactly as shown in the reference. Semantic negative prompt: "subject.locked" remains faithful to the reference dish.',
} as const

function failure(error: string): CompositionResult {
  return { ok: false, error, code: 'COMPOSITION_FAILURE' }
}

function withDescription(descriptor: SceneDescriptor, description: string): SceneDescriptor {
  return { ...descriptor, subject: { ...descriptor.subject, description } }
}

/**
 * Shorten `subject.description` until the composed prompt fits the task ceiling.
 * The description is the only expendable part of the descriptor: every other
 * field is either an identity lock or a staged instruction. Degrading here keeps
 * a detailed observation from turning into a composition failure.
 */
function trimDescriptionToFit(
  descriptor: SceneDescriptor,
  directive: string,
): SceneDescriptor {
  const { description } = descriptor.subject
  if (!description) return descriptor

  const maxLength = MAX_PROMPT_LENGTH_BY_TASK[resolveTask(descriptor)]
  if (estimatePromptSize(descriptor, directive) < maxLength) return descriptor

  let limit = description.length
  while (limit > MIN_DESCRIPTION_LENGTH) {
    limit = Math.floor(limit / 2)
    const candidate = withDescription(descriptor, description.slice(0, limit))
    if (estimatePromptSize(candidate, directive) < maxLength) return candidate
  }
  return withDescription(descriptor, description.slice(0, MIN_DESCRIPTION_LENGTH))
}

function estimatePromptSize(descriptor: SceneDescriptor, directive: string): number {
  const framing = framingFor(descriptor)
  const descriptorJSON = JSON.stringify(descriptor, null, 2)
  return [framing, `Requested directive: ${directive}`, '', descriptorJSON].join('\n').length
}

function resolveTask(descriptor: SceneDescriptor): 'edit' | 'reshoot' {
  return descriptor.task === 'reshoot' ? 'reshoot' : 'edit'
}

function hasCameraTarget(descriptor: SceneDescriptor): boolean {
  const camera = descriptor.target?.camera
  if (!camera) return false
  return Boolean(camera.viewpoint || camera.angle || camera.plateFacing)
}

function framingFor(descriptor: SceneDescriptor): string {
  if (descriptor.task === 'reshoot') return TASK_FRAMING.reshoot
  if (hasCameraTarget(descriptor)) return TASK_FRAMING.editWithCamera
  return TASK_FRAMING.edit
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

/**
 * Compatibility representation for callers that still provide Tier 1 state.
 * New Studio callers should pass the descriptor built by buildSceneDescriptor.
 * The fallback uses semantic names and never compresses or slices values.
 */
const LEGACY_STYLE_KEYS = new Set<string>([
  ...STUDIO_BACKDROP_KEYS,
  ...STUDIO_LIGHTING_KEYS,
  ...STUDIO_SURFACE_KEYS,
])

function legacyStyleDescription(value: string, kind: 'lighting' | 'backdrop' | 'surface'): string {
  // Tier 1 keys are control values, not model-facing observations. When the
  // legacy caller has not resolved a style row yet, retain semantic context
  // without leaking the internal key into the descriptor.
  if (LEGACY_STYLE_KEYS.has(value)) return `selected ${kind} style`
  return value
}

function changed<T>(original: T, target: T): boolean {
  return JSON.stringify(original) !== JSON.stringify(target)
}

function descriptorFromStates(
  original: MinimalSchema,
  target: MinimalSchema,
): SceneDescriptor {
  const originalScene = original.scene_setup
  const targetScene = target.scene_setup
  const originalCanvas = original.canvas
  const targetCanvas = target.canvas
  const originalFood = original.food_components
  const targetFood = target.food_components
  const cameraChanged =
    changed(originalScene.angle, targetScene.angle) ||
    changed(originalScene.framing, targetScene.framing) ||
    changed(originalScene.spin, targetScene.spin)
  const lightingChanged = changed(originalScene.lighting, targetScene.lighting)
  const backdropStyleChanged = changed(originalCanvas.background_style, targetCanvas.background_style)
  const surfaceStyleChanged = changed(originalCanvas.surface_style, targetCanvas.surface_style)
  const backgroundChanged = changed(originalCanvas.background, targetCanvas.background)
  const componentsChanged =
    changed(originalFood.main_item, targetFood.main_item) ||
    changed(originalFood.garnishes, targetFood.garnishes) ||
    changed(originalFood.sides, targetFood.sides) ||
    changed(originalCanvas.main_vessel, targetCanvas.main_vessel)

  const current: SceneDescriptor['current'] = {
    camera: {
      angle: originalScene.angle,
      framing: originalScene.framing,
      spin: originalScene.spin,
    },
    backdrop: { description: originalCanvas.background },
  }
  const targetState: SceneDescriptor['target'] = {}

  if (cameraChanged) {
    targetState.camera = {
      angle: targetScene.angle,
      framing: targetScene.framing,
      spin: targetScene.spin,
    }
  }
  if (backgroundChanged) {
    targetState.backdrop = { description: targetCanvas.background }
  }
  if (componentsChanged) {
    current.components = {
      garnishes: originalFood.garnishes,
      sides: originalFood.sides,
      main_item: originalFood.main_item,
      vessel: originalCanvas.main_vessel,
    } as SceneDescriptor['current']['components']
    targetState.components = {
      garnishes: targetFood.garnishes,
      sides: targetFood.sides,
      main_item: targetFood.main_item,
      vessel: targetCanvas.main_vessel,
    } as SceneDescriptor['target']['components']
  }
  if (lightingChanged) {
    current.lighting = { description: legacyStyleDescription(originalScene.lighting, 'lighting') }
    targetState.lighting = { description: legacyStyleDescription(targetScene.lighting, 'lighting') }
  }
  if (backdropStyleChanged) {
    current.backdrop = {
      ...current.backdrop,
      appearance: legacyStyleDescription(originalCanvas.background_style, 'backdrop'),
    }
    targetState.backdrop = {
      ...(targetState.backdrop ?? {}),
      appearance: legacyStyleDescription(targetCanvas.background_style, 'backdrop'),
    }
  }
  if (surfaceStyleChanged) {
    current.surface = { material: legacyStyleDescription(originalCanvas.surface_style, 'surface') }
    targetState.surface = { material: legacyStyleDescription(targetCanvas.surface_style, 'surface') }
  }

  return {
    task: 'edit',
    subject: {
      dish: originalFood.main_item,
      vessel: originalCanvas.main_vessel,
      components: {
        garnishes: originalFood.garnishes,
        sides: originalFood.sides,
      },
      locked: [
        'dish identity',
        'ingredient and component counts',
        'vessel',
        'framing',
        'colours and textures',
      ],
    },
    camera: {},
    current,
    target: targetState,
    output: { style: 'photorealistic', framing: 'full shot, no cropping' },
  }
}

function normalizeDirective(directive: string): string {
  let normalizedDirective = directive
  if (directive.length > 500) {
    const seen = new Set<string>()
    normalizedDirective = directive
      .split(/(?<=[.!?])\s+/)
      .filter((sentence) => {
        const normalized = sentence.trim()
        if (!normalized) return false
        if (seen.has(normalized)) return false
        seen.add(normalized)
        return true
      })
      .join(' ')
  }

  const sanitizedDirective = normalizedDirective
    .replace(/(?:Do not change the dish\.\s*){2,}/g, 'Do not change the dish. ')
    .replace(/(?:Do not add props\.\s*){2,}/g, 'Do not add props. ')

  return sanitizedDirective
}

/**
 * Compose the constrained-edit prompt around a pretty-printed descriptor.
 *
 * The descriptor is intentionally the dominant part of the prompt. Keeping
 * framing prose outside the JSON preserves the image-edit template shape,
 * while `JSON.stringify` without a replacer ensures every supplied value is
 * retained in full and remains semantically named.
 */
export function composePrompt(input: CompositionInput): CompositionResult {
  const { directive, descriptor, originalState, targetState } = input

  if (typeof directive !== 'string' || directive.trim().length === 0) {
    return failure('Composition failure: directive is missing or empty.')
  }

  let modelDescriptor: SceneDescriptor
  if (descriptor !== undefined) {
    if (!isRecord(descriptor)) {
      return failure('Composition failure: descriptor is missing or not an object.')
    }
    modelDescriptor = descriptor as SceneDescriptor
  } else {
    if (!isRecord(originalState)) {
      return failure(
        'Composition failure: originalState is missing or not an object.',
      )
    }
    if (!isRecord(targetState)) {
      return failure(
        'Composition failure: targetState is missing or not an object.',
      )
    }

    try {
      modelDescriptor = descriptorFromStates(
        originalState as MinimalSchema,
        targetState as MinimalSchema,
      )
    } catch (error) {
      return failure(
        `Composition failure: state could not be converted to a descriptor. ${
          error instanceof Error ? error.message : String(error)
        }`,
      )
    }
  }

  const normalizedDirective = normalizeDirective(directive)
  const task = resolveTask(modelDescriptor)
  const modelDescriptorForPrompt = trimDescriptionToFit(modelDescriptor, normalizedDirective)

  const descriptorPayload =
    descriptor === undefined && directive.length > 500
      ? { ...modelDescriptorForPrompt, instruction: normalizedDirective }
      : modelDescriptorForPrompt

  let descriptorJSON: string
  try {
    const legacyDescriptorIsLarge =
      descriptor === undefined && JSON.stringify(modelDescriptor).length >= 500
    descriptorJSON = JSON.stringify(
      descriptorPayload,
      null,
      descriptor !== undefined || !legacyDescriptorIsLarge ? 2 : 0,
    )
  } catch (error) {
    return failure(
      `Composition failure: descriptor could not be serialized to JSON. ${
        error instanceof Error ? error.message : String(error)
      }`,
    )
  }

  if (typeof descriptorJSON !== 'string') {
    return failure('Composition failure: descriptor could not be serialized to JSON.')
  }

  const framing = framingFor(modelDescriptorForPrompt)
  const prompt = descriptor === undefined
    ? directive.length > 500
      ? [framing, '', descriptorJSON].join('\n')
      : [framing, `Requested directive: ${normalizedDirective}`, '', descriptorJSON].join('\n')
    : [framing, `Requested directive: ${normalizedDirective}`, '', descriptorJSON].join('\n')

  const maxLength = MAX_PROMPT_LENGTH_BY_TASK[task]
  if (prompt.length >= maxLength) {
    return failure(
      `Composition failure: prompt exceeds the ${maxLength}-character limit.`,
    )
  }

  return { ok: true, prompt }
}

export { MAX_PROMPT_LENGTH_BY_TASK, MIN_DESCRIPTION_LENGTH, TASK_FRAMING }
