/**
 * Photo Control — Prompt Composer
 *
 * Assembles the model-facing Tier 2 scene descriptor with a concise,
 * constrained-edit wrapper. The descriptor is built by `scene-descriptor` for
 * the Studio path; the legacy state pair remains accepted for callers that
 * have not yet migrated to pass the descriptor directly.
 */

import type { MinimalSchema } from './minimal-schema'
import type { SceneDescriptor } from './scene-descriptor'

// ============================================================================
// Types
// ============================================================================

/** Inputs accepted while callers migrate from Tier 1 states to Tier 2. */
export interface CompositionInput {
  /** Natural-language instruction generated by the directive generator. */
  directive: string
  /** Model-facing Tier 2 descriptor, preferred by the Studio path. */
  descriptor?: SceneDescriptor
  /** Legacy Tier 1 state retained for existing admin and route callers. */
  originalState?: MinimalSchema
  /** Legacy Tier 1 target state retained for existing admin and route callers. */
  targetState?: MinimalSchema
}

/** Result of composing a prompt; the failure code is part of the route contract. */
export type CompositionResult =
  | { ok: true; prompt: string }
  | { ok: false; error: string; code: 'COMPOSITION_FAILURE' }

/** Convenience error for callers that prefer exceptions over result checking. */
export class CompositionFailureError extends Error {
  readonly code = 'COMPOSITION_FAILURE' as const

  constructor(message: string) {
    super(message)
    this.name = 'CompositionFailureError'
  }
}

const MAX_PROMPT_LENGTH = 2492

/**
 * This is deliberately a real edit wrapper rather than a one-line preamble.
 * `locked` is the semantic negative prompt: it identifies the pixel-faithful
 * content without repeating a prohibition wall from every style row.
 */
const EDIT_FRAMING =
  'Constrained edit: change only what "target" names; keep everything else exactly as-is and preserve the original composition. Semantic negative prompt: everything in "subject.locked" remains pixel-faithful.'

function failure(error: string): CompositionResult {
  return { ok: false, error, code: 'COMPOSITION_FAILURE' }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

/**
 * Compatibility representation for callers that still provide Tier 1 state.
 * New Studio callers should pass the descriptor built by buildSceneDescriptor.
 * The fallback uses semantic names and never compresses or slices values.
 */
function descriptorFromStates(
  original: MinimalSchema,
  target: MinimalSchema,
): SceneDescriptor {
  const originalScene = original.scene_setup
  const targetScene = target.scene_setup
  const originalCanvas = original.canvas
  const targetCanvas = target.canvas
  const originalFood = original.food_components
  const targetFood = target.food_components

  const subject = {
    dish: originalFood.main_item,
    vessel: originalCanvas.main_vessel,
    components: {
      garnishes: originalFood.garnishes,
      sides: originalFood.sides,
    },
    locked: [
      'dish identity',
      'ingredient and component counts',
      'vessel',
      'framing',
      'colours and textures',
    ],
  }

  return {
    task: 'edit',
    subject,
    camera: {
      angle: targetScene.angle,
      framing: targetScene.framing,
      spin: targetScene.spin,
    },
    current: {
      camera: {
        angle: originalScene.angle,
        framing: originalScene.framing,
        spin: originalScene.spin,
      },
      backdrop: { description: originalCanvas.background },
      components: {
        garnishes: originalFood.garnishes,
        sides: originalFood.sides,
      },
    },
    target: {
      camera: {
        angle: targetScene.angle,
        framing: targetScene.framing,
        spin: targetScene.spin,
      },
      backdrop: { description: targetCanvas.background },
      components: {
        garnishes: targetFood.garnishes,
        sides: targetFood.sides,
      },
    },
    output: { style: 'photorealistic', framing: 'full shot, no cropping' },
  }
}

/**
 * Compose the constrained-edit prompt around a pretty-printed descriptor.
 *
 * The descriptor is intentionally the dominant part of the prompt. Keeping
 * framing prose outside the JSON preserves the image-edit template shape,
 * while `JSON.stringify` without a replacer ensures every supplied value is
 * retained in full and remains semantically named.
 */
export function composePrompt(input: CompositionInput): CompositionResult {
  const { directive, descriptor, originalState, targetState } = input

  if (typeof directive !== 'string' || directive.trim().length === 0) {
    return failure('Composition failure: directive is missing or empty.')
  }

  let modelDescriptor: SceneDescriptor
  if (descriptor !== undefined) {
    if (!isRecord(descriptor)) {
      return failure('Composition failure: descriptor is missing or not an object.')
    }
    modelDescriptor = descriptor as SceneDescriptor
  } else {
    if (!isRecord(originalState)) {
      return failure(
        'Composition failure: originalState is missing or not an object.',
      )
    }
    if (!isRecord(targetState)) {
      return failure(
        'Composition failure: targetState is missing or not an object.',
      )
    }

    try {
      modelDescriptor = descriptorFromStates(
        originalState as MinimalSchema,
        targetState as MinimalSchema,
      )
    } catch (error) {
      return failure(
        `Composition failure: state could not be converted to a descriptor. ${
          error instanceof Error ? error.message : String(error)
        }`,
      )
    }
  }

  let descriptorJSON: string
  try {
    descriptorJSON = JSON.stringify(modelDescriptor, null, 2)
  } catch (error) {
    return failure(
      `Composition failure: descriptor could not be serialized to JSON. ${
        error instanceof Error ? error.message : String(error)
      }`,
    )
  }

  if (typeof descriptorJSON !== 'string') {
    return failure('Composition failure: descriptor could not be serialized to JSON.')
  }

  const prompt = [
    EDIT_FRAMING,
    `Requested directive: ${directive}`,
    '',
    descriptorJSON,
  ].join('\n')

  if (prompt.length >= MAX_PROMPT_LENGTH) {
    return failure(
      `Composition failure: prompt exceeds the ${MAX_PROMPT_LENGTH}-character limit.`,
    )
  }

  return { ok: true, prompt }
}
