import { Metadata } from 'next'
import { requireAdmin } from '@/lib/auth-utils'
import { PromptReviewClient } from './prompt-review-client'

export const metadata: Metadata = {
  title: 'Prompt Review | Admin | GridMenu',
  description: 'Inspect and compare prompts generated by the V2 narrative engine',
}

export const dynamic = 'force-dynamic'

export default async function PromptReviewPage() {
  await requireAdmin()
  return <PromptReviewClient />
}
