export const ANALYTICS_EVENTS = {
  HOMEPAGE_VIEWED: 'homepage_viewed',
  CTA_CLICKED: 'cta_clicked',
  PRICING_VIEWED: 'pricing_viewed',
  SIGNUP_STARTED: 'signup_started',
  SIGNUP_COMPLETED: 'signup_completed',
  LOGIN_COMPLETED: 'login_completed',
  MENU_CREATION_STARTED: 'menu_creation_started',
  MENU_IMAGE_UPLOADED: 'menu_image_uploaded',
  MENU_EXTRACTION_STARTED: 'menu_extraction_started',
  MENU_EXTRACTION_COMPLETED: 'menu_extraction_completed',
  MENU_EXTRACTION_FAILED: 'menu_extraction_failed',
  MENU_ITEM_EDITED: 'menu_item_edited',
  TEMPLATE_SELECTED: 'template_selected',
  FOOD_PHOTO_GENERATION_STARTED: 'food_photo_generation_started',
  FOOD_PHOTO_GENERATED: 'food_photo_generated',
  FOOD_PHOTO_GENERATION_FAILED: 'food_photo_generation_failed',
  PDF_EXPORT_STARTED: 'pdf_export_started',
  PDF_EXPORTED: 'pdf_exported',
  PDF_EXPORT_FAILED: 'pdf_export_failed',
  CHECKOUT_STARTED: 'checkout_started',
  SUBSCRIPTION_STARTED: 'subscription_started',
  ADMIN_ANALYTICS_DISABLED: 'admin_analytics_disabled',
  ADMIN_ANALYTICS_ENABLED: 'admin_analytics_enabled',
  FIRST_TEMPLATE_VISIT: 'first_template_visit',
  STUDIO_VIEWED: 'studio_viewed',
  STUDIO_ACCESS_DENIED: 'studio_access_denied',
  STUDIO_ONBOARDING_VIEWED: 'studio_onboarding_viewed',
  STUDIO_UPLOAD_STARTED: 'studio_upload_started',
  STUDIO_UPLOAD_COMPLETED: 'studio_upload_completed',
  STUDIO_UPLOAD_REJECTED: 'studio_upload_rejected',
  STUDIO_EXTRACTION_COMPLETED: 'studio_extraction_completed',
  STUDIO_EXTRACTION_FAILED: 'studio_extraction_failed',
  STUDIO_GENERATION_STARTED: 'studio_generation_started',
  STUDIO_GENERATION_COMPLETED: 'studio_generation_completed',
  STUDIO_GENERATION_FAILED: 'studio_generation_failed',
  STUDIO_GENERATION_BLOCKED_CREDITS: 'studio_generation_blocked_credits',
  STUDIO_GENERATION_BLOCKED_DISH: 'studio_generation_blocked_dish',
  STUDIO_IMAGE_DOWNLOADED: 'studio_image_downloaded',
  STUDIO_IMAGE_REUSED: 'studio_image_reused',
  STUDIO_FEEDBACK_SUBMITTED: 'studio_feedback_submitted',
  STUDIO_FEEDBACK_DISMISSED: 'studio_feedback_dismissed',
} as const

export type AnalyticsEventName = (typeof ANALYTICS_EVENTS)[keyof typeof ANALYTICS_EVENTS]
